### ISSUE TITLE
`mozilla.social` embed is blocked/broken

### ISSUE THREAD

**Issue by kittenswolf** [mozilla-spidermonkey/mozilla-spidermonkey.github.io#148]
On https://spidermonkey.dev/blog/2023/08/07/newsletter-firefox-116-117.html, the `mozilla.social` embed is blocked/broken.

It points to `https://mozilla.social/@stevetex/110696689018983577/embed`, but that leads to a 404 page. Removing the `/embed` shows the post, so maybe the embed url changed?

![grafik](https://github.com/mozilla-spidermonkey/spidermonkey.dev/assets/26834699/9f6400e4-1a20-49b3-82ad-e8913a04983d)

**Comment by jandem** [comment]
Thanks for the report.

mozilla.social now uses Elk and I wonder if that broke this. I'll ask about this internally and if there's no short-term plan to fix this I can change the blog post.
