### ISSUE TITLE
Tighten paragraph spacing?

### ISSUE THREAD

**Issue by mgaudet** [mozilla-spidermonkey/mozilla-spidermonkey.github.io#154]
I would argue we should change our CSS to fix our paragraph spacing. I find our blog posts, especially the newsletters a bit distracting to read as a result of the huge paragraph spaces.

**Comment by willyelm** [comment]
I agree that the content is easier to follow if we decrease the paragraph spacing. The best thing we can do is to stick to the [WCAG22](https://www.w3.org/TR/WCAG22/#text-spacing) guidelines which would reduce the spacing by 8px from 40px to 32px(2 times the font size).
