### ISSUE TITLE
Tweak mobile view

### ISSUE THREAD

**Issue by codehag** [mozilla-spidermonkey/mozilla-spidermonkey.github.io#26]
This is:

tasks:
* [x] 100% about spacing and testing for different mobile widths
* [x] Checking the menu that it fits on all devices

At the moment it looks like this: 

<img width="446" alt="Screenshot 2021-04-26 at 19 22 34" src="https://user-images.githubusercontent.com/26968615/116396293-80050100-a825-11eb-9008-8996ccb695e1.png">

The spacing between elements could be improved. We also want to make sure that the links appear correctly / check if we need a hamburger menu.

**Comment by arai-a** [comment]
I'll take

**Comment by codehag** [comment]
Arai did this already
