### ISSUE TITLE
Menu tweaks

### ISSUE THREAD

**Issue by codehag** [mozilla-spidermonkey/mozilla-spidermonkey.github.io#28]
I have an initial menu set up, but we want to work on the spacing and separation:

Tasks here are 

* [x] fixing up the styling / padding
* [x] updating the links so they point to the appropriate pages/page segments
* [x] indicate which page is selected, if it is not the home page

In detail, we have:

<img width="610" alt="Screenshot 2021-04-28 at 13 32 50" src="https://user-images.githubusercontent.com/26968615/116396960-4680c580-a826-11eb-9cce-2b98f7d1f187.png">

We want:

<img width="328" alt="Screenshot 2021-04-28 at 13 33 01" src="https://user-images.githubusercontent.com/26968615/116396969-497bb600-a826-11eb-8d47-df62efc30832.png">

At the moment, there is also no visual queue if you hover -- I don't have strong opinions there so whatever works. Maybe inverting the colours and having a yellow background with blue text on hover, similar to title text:

<img width="153" alt="Screenshot 2021-04-28 at 13 34 07" src="https://user-images.githubusercontent.com/26968615/116397081-6d3efc00-a826-11eb-8c27-af0ab9a68064.png">

Minus the spelling mistake, for example

**Comment by jandem** [comment]
I made some of these changes (menu items generated from Jekyll pages, line between items).

We still need the "selected page" styling.

**Comment by jandem** [comment]
I added the suggested hover style.

It's also used for the active page, but it may be too much for that. WDYT @yulia?

**Comment by codehag** [comment]
Looks great to me. Looking at it in light mode -- we need to tweek the highlight color (to black) but otherwise looks fab.

**Comment by codehag** [comment]
This is done!
