### ISSUE TITLE
Footer Styling

### ISSUE THREAD

**Issue by codehag** [mozilla-spidermonkey/mozilla-spidermonkey.github.io#30]
The footer is currently unstyled

Tasks:

* [ ] Decide on an organizing of information. I would propose social media links etc on the left, content links and copyright on the right
* [ ] add svg images for any social media links
* [ ] general styling

What we have now:

<img width="1349" alt="Screenshot 2021-04-28 at 13 37 38" src="https://user-images.githubusercontent.com/26968615/116397482-eccccb00-a826-11eb-932a-0cadff26ed0b.png">

We need to introduce back the twitter icon. We also likely want to add links to the blog, contributing, and also maybe a code of conduct.

**Comment by allstarschh** [comment]
I am working on this

**Comment by allstarschh** [comment]
WIP: https://github.com/allstarschh/mozilla-spidermonkey.github.io/commit/2f2fae5ade1a7daba214fb5cb1c589daca224834

**Comment by codehag** [comment]
merged
