### ISSUE TITLE
Picking a colour scheme for the code blocks

### ISSUE THREAD

**Issue by codehag** [mozilla-spidermonkey/mozilla-spidermonkey.github.io#44]
We need a light mode and a dark mode:

<img width="893" alt="Screenshot 2021-04-28 at 20 30 50" src="https://user-images.githubusercontent.com/26968615/116454795-a7c58a80-a860-11eb-8c7f-1911f69ca2a7.png">

**Comment by jandem** [comment]
I changed the dark theme to use "hybrid".  For the light theme I think "default" isn't too bad, at least for now.

All available themes are listed here: https://highlightjs.org/static/demo/ It's easy to experiment with other themes by changing the css file names in default.html
