### ISSUE TITLE
Font Selection

### ISSUE THREAD

**Issue by codehag** [mozilla-spidermonkey/mozilla-spidermonkey.github.io#47]
I've narrowed it to 3: PT serif, PT sans, and Fira.

Voting can be emojis, 🎉 for PT serif, 🚀 for PT sans, ❤️ for Fira.

PT Serif
<img width="797" alt="Screenshot 2021-04-29 at 10 28 32" src="https://user-images.githubusercontent.com/26968615/116522696-c4e87080-a8d5-11eb-8d06-7ebaae8b3ab2.png">

PT Sans
<img width="799" alt="Screenshot 2021-04-29 at 10 28 20" src="https://user-images.githubusercontent.com/26968615/116522701-c6b23400-a8d5-11eb-908b-928d09793f86.png">

Fira
<img width="787" alt="Screenshot 2021-04-29 at 10 28 06" src="https://user-images.githubusercontent.com/26968615/116522706-c7e36100-a8d5-11eb-8ece-304039f04494.png">

**Comment by codehag** [comment]
If you have another font that you like, we can try that too

**Comment by jandem** [comment]
Playing with this a bit in devtools, I really like the `PT-Sans-S55` font. Does the screenshot use `PT-Sans-C55`? That one looks a bit worse to me because it has more spacing between the letters, or something.

**Comment by codehag** [comment]
Yes, screenshot uses C55, S55 might be better (do you have a screenshot?)

**Comment by jandem** [comment]
PT-Sans-S55:
<img width="670" alt="Screenshot 2021-04-30 at 09 01 28" src="https://user-images.githubusercontent.com/411344/116660051-bf9d2b80-a992-11eb-9e17-8dc5ed49d601.png">

**Comment by codehag** [comment]
yeah.. that looks good...

**Comment by codehag** [comment]
Done for now
